### ISSUE TITLE
Enabling proposer fails with "The provided prover endpoint is not functional"

### ISSUE THREAD

**Issue by rihardsgrislis** [taikoxyz/simple-taiko-node#190]
Hey,

Got my node synced up and wanted to enable proposer.

Ran:
`stn config proposer`

> ✔ The node is currently not configured as a proposer. Would you like to enable it? · yes
> ✔ Select a prover endpoint configuration: · Enter a prover endpoint
> ✔ Please enter your desired prover endpoint · http://taiko-a6-prover.zkpool.io:9876
> The provided prover endpoint is not functional.
> Failed to initialize or update proposer configuration.
> No changes made to proposer configuration.

Why is that?

The documentation at https://docs.taiko.xyz/guides/enable-a-proposer/ only says to run the `stn config proposer` command but doesn't provide instructions for the endpoint but I assume it's the same as for simple-taiko-node so I got the prover endpoint from: https://docs.taiko.xyz/resources/prover-marketplace

**Comment by SrWilbur** [comment]
same for here.

In Discord some people say to change:
http://taiko-a6-prover.zkpool.io:9876/

for

http://taiko-a6-prover.zkpool.io 

(Without port number)

IDK, I dont find documentation

**Comment by ramshazz** [comment]
The issue you're encountering could be due to several reasons. Let's break down the process and potential issues:

Prover Endpoint Accessibility: The error message you received indicates that the prover endpoint http://taiko-a6-prover.zkpool.io:9876 is not functional. This could mean the endpoint is down, experiencing issues, or there's a network connectivity problem from your node to the prover endpoint. It's possible that the prover endpoint is not available or has changed since you last checked.

Prover Endpoint Correctness: If you obtained the prover endpoint from the Taiko documentation or a prover marketplace, it should theoretically be correct. However, there could be typos, or the endpoint information might have been updated or changed after you accessed it.

Network Configuration: Ensure that your network allows outbound connections to the prover endpoint. Firewalls or network security settings could block the connection to the prover's port.

Documentation and Resources: While the documentation provided a general guide on enabling a proposer, specifics regarding prover endpoints might require more detailed guidance. The fact that the endpoint isn't working suggests either a temporary issue with the prover or a need for updated documentation.

Steps to Troubleshoot
Verify Prover Endpoint: Check the prover marketplace or any official announcements for any updates or changes to the prover endpoints. Provers might change their endpoints, ports, or go offline for maintenance.

Network Connectivity: Test the network connectivity to the prover endpoint using tools like ping or curl to ensure your node can reach the endpoint. For example, you could run a command like curl http://taiko-a6-prover.zkpool.io:9876 to see if you get a response.

Consult Community or Support Channels: If the issue persists, reaching out to the Taiko community or support channels can be helpful. There might be others who have faced similar issues, or there could be announcements regarding known issues with certain provers.

Check for Documentation Updates: Since blockchain technologies and their ecosystems evolve rapidly, it's worthwhile to check for any updates or additional guides that might have been added after your initial setup.

If after these steps you're still facing issues, it might be beneficial to consider selecting a different prover endpoint to http://taiko-a6-prover.zkpool.io/

Also read this article

https://docs.blockpi.io/guides-for-web-3.0-users/how-to-use-blockpi/customize-endpoint-advanced-features#archive-mode

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/simple-taiko-node/issues/190#issuecomment-1986868898
