### ISSUE TITLE
failed to insert new head to L2 execution engine

### ISSUE THREAD

**Issue by Venoox** [taikoxyz/simple-taiko-node#55]
```
simple-taiko-node-taiko_client_driver-1          | ERROR[06-08|12:39:58.631] Block batch iterator callback error      error="failed to insert new head to L2 execution engine: missing trie node 49c392582ec938adb8a9823446d90cc0418e576e1a19d9f9fddc08961e016a05 (path ) <nil>"
```

When running simple-taiko-node and restarting it, it starts showing this error and prover doesn't work anymore. The only way to fix it is to delete volumes and start again.

Possible cause is docker forcefully stopping it after 10 seconds

**Comment by davidtaikocha** [comment]
Since for A3 network, when we build a pending block's anchor tx, we need to query the "L1signalRoot" by an `eth_getProof` RPC query (now we have ~300 L2 pending blocks in avg), but a Sepolia geth's full node will only store last 128 blocks' state trie, so if a user's Sepolia provider only provides "Sepolia full node endpoint" but not "Sepolia archived node enpoint", u will get this error (missing trie node). And the solution is using a archived Sepolia node's endpoint.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/13942

**Comment by Venoox** [comment]
I'm using Alchemy, don't they use archive node?

**Comment by weirongbo** [comment]
How do I determine whether an RPC node is a full node or an archive node?
